In [11]:
#Crear archivo de texto plano/ formato libre

import numpy as np 

In [2]:
data = np.random.normal(size=500000)

In [5]:
data.size


500000

In [12]:
fp = open("prueba.txt", "w")
fp.write("# Este es un archivo de texto\n")#salto de linea!! \n

#Importante cerrar los archivos para que los procesos de escritura se completen
fp.close()

30

In [15]:
#Como guardar un archivo

with open("data.txt", "w") as f: #Objeto tipo archivo
    for i in data:
        f.write("{:.5f}\n".format(i)) #Archivo de texto que contiene datos con 5 decimales en formato flotante
        
        
#Recomendable usar with

In [18]:
#Almacenar datos de modo que cada linea sea un registro y cada columna un campo separados por espacio (tabla)

with open("data.txt", "w") as f:
    for i in range(len(data)):
        f.write("{:d} {:.5f}\n".format(i, data[i])) 
        
# :d formato del dato 
# :.xf cantidad de decimales 

In [4]:
#Para leer un archivo: Indicador de lectura "r" a "open"

f = open("data.txt", "r") #abrir el archivo
l = f.readlines() #devuelve una lista de lineas tipo string

#Readline me devuelve una linea, la linea en la que esta el indicador
l1 = f.readline()

#Para volver al principio o final del archivo usamos seek
s = f.seek(0) #vuelve al inicio del archivo. Se resetea el archivo

s



0

In [5]:
l1 = f.readline()
l1

'0 -0.12580\n'

In [6]:
#Cada elemento lo podemos convertir a numeros conociendo el formato

l1.split() #elementos separados

l1.split()[1] #seleccionar uno en especifico

float(l1.split()[1]) #lo convertimos a flotante


-0.1258

In [7]:
type(l1.split()[1])

str

In [2]:
###Trabajar en la memoria ram es mas rapido que trabajar en el disco duro###

In [8]:
f.seek(0)

la, lb = [], []
for line in f.readlines():
    la.append(int(line.split()[0]))
    lb.append(float(line.split()[1]))
    

In [10]:
lb

[-0.1258,
 0.1525,
 -0.82592,
 1.70259,
 -1.10012,
 -0.70818,
 1.36331,
 -0.40905,
 0.14698,
 -1.51438,
 1.77591,
 0.04262,
 -0.38477,
 -0.23732,
 0.22358,
 0.10499,
 0.11323,
 2.13154,
 0.50163,
 -1.3827,
 1.33827,
 1.0624,
 -0.27989,
 0.4075,
 1.16363,
 1.66669,
 -0.97171,
 0.57187,
 -0.13968,
 -1.09355,
 2.38913,
 -1.83445,
 -1.16254,
 0.03846,
 -1.7487,
 0.05927,
 -0.21479,
 -0.45738,
 1.2658,
 -0.36627,
 -0.50114,
 -0.43558,
 0.93189,
 0.0046,
 0.07852,
 0.61755,
 -0.10661,
 0.83971,
 -1.18784,
 0.02429,
 0.45855,
 1.82159,
 0.66422,
 0.29968,
 -0.38876,
 -0.43753,
 -0.07947,
 1.12709,
 -1.30052,
 -1.28711,
 -1.38667,
 -0.18218,
 0.92229,
 -0.70393,
 -1.6502,
 -0.36684,
 1.85791,
 0.4343,
 -1.53368,
 1.78564,
 -0.99672,
 -1.16024,
 -0.35639,
 0.4216,
 1.60298,
 -1.22947,
 0.23437,
 -1.16047,
 -0.41141,
 0.50643,
 0.4545,
 2.55872,
 -1.3549,
 -1.23272,
 -0.48157,
 -0.3257,
 -0.16621,
 -0.03242,
 -0.34631,
 -1.95766,
 -0.37395,
 0.89468,
 -0.15829,
 -0.01971,
 0.77322,
 -0.68234,
 -

In [13]:
#Vamos a trabajar los datos con alguna libreria numerica 

np2 = np.array(lb)
np2

array([-0.1258 ,  0.1525 , -0.82592, ...,  1.3645 ,  0.43019, -0.86687])

In [14]:
#Numpy trae sus propios metodos para cargar archivos de texto 

npdata1 = np.loadtxt("data.txt")

In [15]:
npdata1

array([[ 0.00000e+00, -1.25800e-01],
       [ 1.00000e+00,  1.52500e-01],
       [ 2.00000e+00, -8.25920e-01],
       ...,
       [ 4.99997e+05,  1.36450e+00],
       [ 4.99998e+05,  4.30190e-01],
       [ 4.99999e+05, -8.66870e-01]])

In [16]:
npdata1.shape


(500000, 2)

In [17]:
npdata1[0][:]

array([ 0.    , -0.1258])

In [19]:
#Carga archivos que realiza una organizacion "por registro", en donde cada elemento del array contiene todos los 
#campos de ese registro 

#Accceder al conjunto completo de los valores de un campo para todos los registros es mas complejo 

#Numpy tambien permite leer priorizando la organizacion por campo en vez de registro 

#Unpack: Toma un registro y lo desempaqueta. Lo trata como 

npdata2 = np.loadtxt("data.txt", unpack=True)
npdata2

array([[ 0.00000e+00,  1.00000e+00,  2.00000e+00, ...,  4.99997e+05,
         4.99998e+05,  4.99999e+05],
       [-1.25800e-01,  1.52500e-01, -8.25920e-01, ...,  1.36450e+00,
         4.30190e-01, -8.66870e-01]])

In [20]:
npdata2.shape


(2, 500000)

In [21]:
#Pandas tambien permite cargar archivos de texto plano aunque esta optimizado para leer CSV y variantes

In [22]:
import pandas as pd 

In [30]:
pddata1 = pd.read_csv("data.txt", header=None, names=["col1", "col2"], index_col=0, sep=" ")
pddata1


col2
col1           
0      -0.12580
1       0.15250
2      -0.82592
3       1.70259
4      -1.10012
...         ...
499995  0.53657
499996 -1.68060
499997  1.36450
499998  0.43019
499999 -0.86687

[500000 rows x 1 columns]

In [31]:
#Pandas permite utilizar iteradores para procesar archivos de textos cuya cantidad de datos es restrictiva segun
#los recursos computacionales (ej. ram)

#Se puede usar chuncks para leer un csv con pandas 


In [40]:
reader = pd.read_csv("data.txt", header=None, names=["col1", "col2"], index_col=0, sep=" ", chunksize=100)
reader


In [42]:
for piece in reader:
    a = piece
    break
    
a

col2
col1         
100   0.33980
101  -2.30931
102  -1.52094
103  -0.30371
104  -0.07841
...       ...
195  -0.05507
196  -0.40888
197  -1.40760
198   0.91985
199  -1.59012

[100 rows x 1 columns]

In [44]:
suma = 0
for piece in reader:
    suma += sum(piece["col2"])

#Esto es equivalente a tomar el DataFrame completo y sumar la col1